#!/usr/bin/env python3
"""Cogging LUT: device COGCAL and/or host-learn → write flash header.

Usage:
  # Bake into firmware (recommended): learn on host, write header, rebuild+flash
  python3 tools/cog_cal.py --host-learn --write src/cog_lut_default.h --no-bootloader
  # Defaults: 20s / 2 rev; exits 1 if bins filled <56/64 or |peak|≤1e-3.

  # Runtime RAM override only (debug; lost on reboot)
  python3 tools/cog_cal.py --device-cal --no-bootloader

  python3 tools/cog_cal.py --host-learn --invert --write src/cog_lut_default.h  # if FF feels sticky
"""
from __future__ import annotations

import argparse
import struct
import sys
import time

try:
	import numpy as np
except ImportError:
	sys.exit("need numpy: pip install numpy")

try:
	import usb.core
	import usb.util
except ImportError:
	sys.exit("need pyusb: pip install pyusb")

VID, PID = 0xACDC, 0x4011
EP_OUT, EP_IN = 0x01, 0x81
TELEM_FMT = "<BBi3hHhhhHh"
COG_LUT_N = 64
COUNTS_PER_REV = 16384
MRAD_2PI = 6283
COG_CAL_S = 10.0


def open_dev():
	dev = usb.core.find(idVendor=VID, idProduct=PID)
	if dev is None:
		raise SystemExit("TinyKnob not found (VID=0xACDC PID=0x4011)")
	for cfg in dev:
		for intf in cfg:
			n = intf.bInterfaceNumber
			try:
				if dev.is_kernel_driver_active(n):
					dev.detach_kernel_driver(n)
			except (NotImplementedError, usb.core.USBError):
				pass
	try:
		dev.set_configuration()
	except usb.core.USBError:
		pass
	cfg = dev.get_active_configuration()
	intf = usb.util.find_descriptor(cfg, bInterfaceClass=0xFF)
	if intf is None:
		raise SystemExit("Vendor interface not found")
	usb.util.claim_interface(dev, intf.bInterfaceNumber)
	return dev


def send(dev, *payload: int) -> None:
	_bulk_write(dev, bytes(payload))


def _bulk_write(dev, data: bytes, timeout: int = 2000, retries: int = 8) -> None:
	last = None
	for _ in range(retries):
		# Drain IN so the device keeps pumping tud_task / telem.
		for _d in range(8):
			try:
				dev.read(EP_IN, 64, timeout=5)
			except usb.core.USBTimeoutError:
				break
			except usb.core.USBError:
				break
		try:
			dev.write(EP_OUT, data, timeout=timeout)
			return
		except usb.core.USBError as e:
			last = e
			time.sleep(0.02)
	raise last if last is not None else usb.core.USBError("bulk write failed")


def goto_mrad(dev, mrad: int) -> None:
	_bulk_write(dev, struct.pack("<Bi", 0x06, int(mrad)))


def read_telem(dev, timeout_ms: int = 50):
	try:
		data = bytes(dev.read(EP_IN, 64, timeout=timeout_ms))
	except usb.core.USBTimeoutError:
		return None
	if len(data) >= 3 and data[0] == 0x5A:
		return None
	if len(data) < 24 or data[0] != 0xA5:
		return None
	(_magic, mode, ang, _da, _db, _dc, _seq, _id, _iq, iq_ref_ma, _vbus, uq_q15) = struct.unpack_from(
		TELEM_FMT, data, 0
	)
	iq_ref = iq_ref_ma / 1000.0
	uq = uq_q15 / 32767.0
	# Outer command units for LUT: prefer iq_ref/IQ_CMD_A (IQ_CMD_A=1 → Amps≡uq units).
	effort = iq_ref if abs(iq_ref) > 1e-4 else uq
	return {"mode": mode, "angle_mrad": ang, "uq": uq, "effort": effort}


def wait_mode(dev, want: int, timeout: float):
	t0 = time.time()
	last = None
	while time.time() - t0 < timeout:
		f = read_telem(dev, timeout_ms=100)
		if f is None:
			continue
		last = f["mode"]
		if f["mode"] == want:
			return f
	raise SystemExit(f"timeout waiting mode={want} (last={last})")


def align(dev) -> dict:
	send(dev, 0x02)
	time.sleep(0.15)
	# Drain IDLE telem so we don't false-trigger on pre-START mode=0.
	for _ in range(30):
		read_telem(dev, timeout_ms=20)
	print("START (align)...")
	send(dev, 0x01)
	# Wait until align actually begins (leave IDLE).
	t0 = time.time()
	while time.time() - t0 < 5.0:
		f = read_telem(dev, timeout_ms=100)
		if f is None:
			continue
		if f["mode"] != 0:
			break
	else:
		raise SystemExit("START did not leave IDLE")
	f = wait_mode(dev, 0, timeout=35.0)
	time.sleep(0.3)
	for _ in range(40):
		read_telem(dev, timeout_ms=20)
	return wait_mode(dev, 0, timeout=3.0)


def write_header(path: str, lut: np.ndarray) -> None:
	assert len(lut) == COG_LUT_N
	lines = [
		"#ifndef _COG_LUT_DEFAULT_H_",
		"#define _COG_LUT_DEFAULT_H_",
		"",
		'#include "pins.h"',
		"",
		"// Generated by tools/cog_cal.py --host-learn --write",
		"// RAM COGCAL can still override at runtime; COGCLEAR reloads this table.",
		"static const float COG_LUT_FLASH[COG_LUT_N] = {",
	]
	vals = [f"{float(x):.8f}f" for x in lut]
	for i in range(0, COG_LUT_N, 8):
		lines.append("\t" + ", ".join(vals[i : i + 8]) + ",")
	lines += ["};", "", "#endif", ""]
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(lines))
	print(f"wrote {path}  peak={float(np.max(np.abs(lut))):.4f}")


def host_learn(dev, seconds: float, revs: float, invert: bool = False) -> np.ndarray:
	"""Slow GOTO while FF off; bin outer Uq vs mech angle → mean-removed LUT."""
	send(dev, 0x09)  # COG_CLEAR → flash (zeros until baked)
	time.sleep(0.05)
	f0 = wait_mode(dev, 0, timeout=3.0)
	a0 = f0["angle_mrad"]
	span = int(revs * MRAD_2PI)
	n_steps = max(int(seconds * 80), 80)
	dt = seconds / n_steps
	sums = np.zeros(COG_LUT_N, dtype=np.float64)
	cnts = np.zeros(COG_LUT_N, dtype=np.int32)
	print(f"host-learn: GOTO {revs} rev / {seconds}s (hands off)...")
	t_end = time.time() + seconds + 0.5
	for i in range(n_steps):
		if time.time() > t_end:
			break
		target = a0 + int(i / max(n_steps - 1, 1) * span)
		goto_mrad(dev, target)
		t_slice = time.time() + dt
		while time.time() < t_slice:
			f = read_telem(dev, timeout_ms=max(int(dt * 400), 5))
			if f is None or f["mode"] != 9:
				continue
			# Map unwrapped angle to one rev via pos-equivalent: angle_mrad / (2π*1000)*CPR
			pos = int(round(f["angle_mrad"] * COUNTS_PER_REV / (MRAD_2PI)))
			r = pos % COUNTS_PER_REV
			if r < 0:
				r += COUNTS_PER_REV
			b = r * COG_LUT_N // COUNTS_PER_REV
			sums[b] += f["effort"]
			cnts[b] += 1
	send(dev, 0x02)
	lut = np.zeros(COG_LUT_N, dtype=np.float64)
	for i in range(COG_LUT_N):
		if cnts[i] > 0:
			lut[i] = sums[i] / cnts[i]
	filled = cnts > 0
	if not np.any(filled):
		raise SystemExit("host-learn: no samples — is CUR_LOOP / GOTO working?")
	# fill gaps
	for i in range(COG_LUT_N):
		if cnts[i] == 0:
			j = (i - 1) % COG_LUT_N
			while cnts[j] == 0 and j != i:
				j = (j - 1) % COG_LUT_N
			lut[i] = lut[j]
	lut -= np.mean(lut)
	if invert:
		lut = -lut
	print(f"bins filled={int(filled.sum())}/{COG_LUT_N}  |lut|peak={float(np.max(np.abs(lut))):.4f} invert={invert}")
	n_fill = int(filled.sum())
	peak = float(np.max(np.abs(lut)))
	if n_fill < 56:
		raise SystemExit(f"host-learn: sparse LUT ({n_fill}/64 filled; need ≥56) — raise --seconds/--revs")
	if peak <= 1e-3:
		raise SystemExit(f"host-learn: |peak|={peak:.6f} too small — check GOTO effort / CUR_LOOP")
	return lut.astype(np.float64)


def device_cal(dev) -> None:
	print(f"device COG_CAL (~{COG_CAL_S:.0f}s)...")
	send(dev, 0x08)
	t0 = time.time()
	saw = False
	while time.time() - t0 < 3.0:
		f = read_telem(dev, timeout_ms=100)
		if f is None:
			continue
		if f["mode"] == 11:
			saw = True
			break
		if 1 <= f["mode"] <= 4:
			raise SystemExit(f"still aligning (mode={f['mode']})")
	if not saw:
		raise SystemExit("COG_CAL did not start")
	wait_mode(dev, 0, timeout=COG_CAL_S + 5.0)
	print("IDLE — RAM LUT override active (not flash until --write + rebuild)")


def main() -> int:
	ap = argparse.ArgumentParser(description=__doc__)
	ap.add_argument("--host-learn", action="store_true", help="sweep GOTO; build LUT on host")
	ap.add_argument("--device-cal", action="store_true", help="firmware COGCAL → RAM override")
	ap.add_argument("--write", type=str, default="", help="write src/cog_lut_default.h")
	ap.add_argument("--invert", action="store_true", help="negate LUT (try if FF feels sticky)")
	ap.add_argument("--seconds", type=float, default=20.0)
	ap.add_argument("--revs", type=float, default=2.0)
	ap.add_argument("--no-bootloader", action="store_true")
	ap.add_argument("--skip-start", action="store_true")
	args = ap.parse_args()
	if not args.host_learn and not args.device_cal:
		args.host_learn = True  # default: bake path

	dev = open_dev()
	if not args.skip_start:
		align(dev)
	else:
		wait_mode(dev, 0, timeout=3.0)

	lut = None
	if args.host_learn:
		lut = host_learn(dev, args.seconds, args.revs, invert=args.invert)
		# Gates already enforced inside host_learn before return.
		if args.write:
			write_header(args.write, lut)
		else:
			print("hint: pass --write src/cog_lut_default.h then rebuild+flash to bake")
	if args.device_cal:
		device_cal(dev)

	print("try SPIN: flick soft vs hard — speed should follow, detent reduced if LUT baked/RAM on")
	if not args.no_bootloader:
		print("UPLOAD → UF2")
		try:
			send(dev, 0x7F)
		except usb.core.USBError:
			pass
	return 0


if __name__ == "__main__":
	sys.exit(main())
