#!/usr/bin/env python3
"""Cogging LUT: device COGCAL and/or host-learn → write flash header.

Usage:
  # Bake into firmware (recommended): learn both directions, write header, rebuild+flash
  python3 tools/cog_cal.py --host-learn --write src/cog_lut_default.h --no-bootloader
  # Defaults: 24s / 12 rev in each direction; each steady-speed pass must fill >=90% of bins.

  # Runtime RAM override only (debug; lost on reboot)
  python3 tools/cog_cal.py --device-cal --no-bootloader

  python3 tools/cog_cal.py --host-learn --invert --write src/cog_lut_default.h  # if FF feels sticky
"""
from __future__ import annotations

import argparse
import struct
import sys
import time

try:
	import numpy as np
except ImportError:
	sys.exit("need numpy: pip install numpy")

try:
	import usb.core
	import usb.util
except ImportError:
	sys.exit("need pyusb: pip install pyusb")

VID, PID = 0xACDC, 0x4011
EP_OUT, EP_IN = 0x01, 0x81
TELEM_FMT = "<BBi3hHhhhHh"
COG_LUT_N = 1024
COUNTS_PER_REV = 16384
MRAD_2PI = 6283
COG_CAL_S = 10.0


def open_dev():
	dev = usb.core.find(idVendor=VID, idProduct=PID)
	if dev is None:
		raise SystemExit("TinyKnob not found (VID=0xACDC PID=0x4011)")
	for cfg in dev:
		for intf in cfg:
			n = intf.bInterfaceNumber
			try:
				if dev.is_kernel_driver_active(n):
					dev.detach_kernel_driver(n)
			except (NotImplementedError, usb.core.USBError):
				pass
	try:
		dev.set_configuration()
	except usb.core.USBError:
		pass
	cfg = dev.get_active_configuration()
	intf = usb.util.find_descriptor(cfg, bInterfaceClass=0xFF)
	if intf is None:
		raise SystemExit("Vendor interface not found")
	usb.util.claim_interface(dev, intf.bInterfaceNumber)
	return dev


def send(dev, *payload: int) -> None:
	_bulk_write(dev, bytes(payload))


def _bulk_write(dev, data: bytes, timeout: int = 2000, retries: int = 8) -> None:
	last = None
	for _ in range(retries):
		# Drain IN so the device keeps pumping tud_task / telem.
		for _d in range(8):
			try:
				dev.read(EP_IN, 64, timeout=5)
			except usb.core.USBTimeoutError:
				break
			except usb.core.USBError:
				break
		try:
			dev.write(EP_OUT, data, timeout=timeout)
			return
		except usb.core.USBError as e:
			last = e
			time.sleep(0.02)
	raise last if last is not None else usb.core.USBError("bulk write failed")


def goto_mrad(dev, mrad: int) -> None:
	_bulk_write(dev, struct.pack("<Bi", 0x06, int(mrad)))


def goto_mrad_stream(dev, mrad: int, velocity_mrad_s: int = 0) -> None:
	"""High-rate GOTO with velocity FF; preserve Bulk IN telemetry."""
	dev.write(EP_OUT, struct.pack("<Bii", 0x06, int(mrad), int(velocity_mrad_s)), timeout=50)


def read_telem(dev, timeout_ms: int = 50):
	try:
		data = bytes(dev.read(EP_IN, 64, timeout=timeout_ms))
	except usb.core.USBTimeoutError:
		return None
	if len(data) >= 3 and data[0] == 0x5A:
		return None
	if len(data) < 24 or data[0] != 0xA5:
		return None
	(_magic, mode, ang, _da, _db, _dc, _seq, _id, _iq, iq_ref_ma, _vbus, uq_q15) = struct.unpack_from(
		TELEM_FMT, data, 0
	)
	direction = struct.unpack_from("<b", data, 24)[0] if len(data) >= 25 else 0
	iq_ref = iq_ref_ma / 1000.0
	uq = uq_q15 / 32767.0
	if direction not in (-1, 1):
		raise SystemExit("firmware telemetry lacks motor dir; flash current firmware before host-learn")
	# iq_ref is post-dir. LUT is replayed before firmware multiplies by dir, so
	# normalize it back to the command domain or dir=-1 inverts compensation.
	effort = iq_ref * direction if abs(iq_ref) > 1e-4 else uq * direction
	return {"mode": mode, "angle_mrad": ang, "uq": uq, "effort": effort, "dir": direction}


def wait_mode(dev, want: int, timeout: float):
	t0 = time.time()
	last = None
	while time.time() - t0 < timeout:
		f = read_telem(dev, timeout_ms=100)
		if f is None:
			continue
		last = f["mode"]
		if f["mode"] == want:
			return f
	raise SystemExit(f"timeout waiting mode={want} (last={last})")


def align(dev) -> dict:
	send(dev, 0x02)
	time.sleep(0.15)
	# Drain IDLE telem so we don't false-trigger on pre-START mode=0.
	for _ in range(30):
		read_telem(dev, timeout_ms=20)
	print("START (align)...")
	send(dev, 0x01)
	# Wait until align actually begins (leave IDLE).
	t0 = time.time()
	while time.time() - t0 < 5.0:
		f = read_telem(dev, timeout_ms=100)
		if f is None:
			continue
		if f["mode"] != 0:
			break
	else:
		raise SystemExit("START did not leave IDLE")
	f = wait_mode(dev, 0, timeout=35.0)
	time.sleep(0.3)
	for _ in range(40):
		read_telem(dev, timeout_ms=20)
	return wait_mode(dev, 0, timeout=3.0)


def write_header(path: str, lut: np.ndarray) -> None:
	assert len(lut) == COG_LUT_N
	lines = [
		"#ifndef _COG_LUT_DEFAULT_H_",
		"#define _COG_LUT_DEFAULT_H_",
		"",
		'#include "pins.h"',
		"",
		"// Generated by bidirectional tools/cog_cal.py --host-learn --write",
		"// RAM COGCAL can still override at runtime; COGCLEAR reloads this table.",
		"static const float COG_LUT_FLASH[COG_LUT_N] = {",
	]
	vals = [f"{float(x):.8f}f" for x in lut]
	for i in range(0, COG_LUT_N, 8):
		lines.append("\t" + ", ".join(vals[i : i + 8]) + ",")
	lines += ["};", "", "#endif", ""]
	with open(path, "w", encoding="utf-8") as f:
		f.write("\n".join(lines))
	print(f"wrote {path}  peak={float(np.max(np.abs(lut))):.4f}")


def collect_pass(dev, span: int, seconds: float, label: str) -> np.ndarray:
	"""Stream a continuous target and retain only steady, correctly directed motion."""
	f0 = wait_mode(dev, 0, timeout=3.0)
	a0 = f0["angle_mrad"]
	rate_hz = 500.0
	n_steps = max(int(seconds * rate_hz), 100)
	dt = seconds / n_steps
	expected = span / seconds
	times: list[float] = []
	angles: list[float] = []
	efforts: list[float] = []
	print(f"  {label}: {abs(span) / MRAD_2PI:.2f} rev / {seconds:.1f}s @ {rate_hz:.0f} Hz")
	t0 = time.monotonic()
	for i in range(n_steps):
		target = a0 + int(i / max(n_steps - 1, 1) * span)
		goto_mrad_stream(dev, target, int(expected))
		next_step = t0 + (i + 1) * dt
		while time.monotonic() < next_step:
			f = read_telem(dev, timeout_ms=2)
			if f is None or f["mode"] != 9:
				continue
			times.append(time.monotonic() - t0)
			angles.append(float(f["angle_mrad"]))
			efforts.append(float(f["effort"]))
	goto_mrad_stream(dev, a0 + span, 0)
	time.sleep(0.2)
	send(dev, 0x02)

	t = np.asarray(times, dtype=np.float64)
	a = np.asarray(angles, dtype=np.float64)
	e = np.asarray(efforts, dtype=np.float64)
	if len(t) < 200:
		raise SystemExit(f"host-learn: {label} captured only {len(t)} telemetry samples")
	sample_dt = float(np.median(np.diff(t)))
	window = max(2, int(round(0.020 / max(sample_dt, 1e-4))))
	vel = np.full(len(t), np.nan, dtype=np.float64)
	vel[window:-window] = (a[2 * window :] - a[: -2 * window]) / (
		t[2 * window :] - t[: -2 * window]
	)
	margin = max(1.0, seconds * 0.12)
	interior = (t >= margin) & (t <= seconds - margin) & np.isfinite(vel)
	directed = interior & (vel * expected > 0.0)
	if int(directed.sum()) < 100:
		raise SystemExit(f"host-learn: {label} never reached steady motion")
	v_dir = vel[directed]
	v_mean = float(np.mean(v_dir))
	v_std = float(np.std(v_dir))
	v_cv = v_std / max(abs(v_mean), 1e-6)
	stable = directed & (np.abs(vel - expected) <= 0.35 * abs(expected))
	accepted = int(stable.sum())
	accept_pct = 100.0 * accepted / max(int(interior.sum()), 1)
	if v_cv > 0.35 or accept_pct < 60.0:
		raise SystemExit(
			f"host-learn: unstable {label}: speed CV={v_cv:.2f}, accepted={accept_pct:.1f}%"
		)

	cnts = np.zeros(COG_LUT_N, dtype=np.int32)
	pos = np.rint(a[stable] * COUNTS_PER_REV / MRAD_2PI).astype(np.int64)
	bins = (np.mod(pos, COUNTS_PER_REV) * COG_LUT_N // COUNTS_PER_REV).astype(np.int64)
	np.add.at(cnts, bins, 1)
	filled = cnts > 0
	n_fill = int(filled.sum())
	median_n = float(np.median(cnts[filled])) if n_fill else 0.0
	print(
		f"    speed={v_mean / 1000.0:.3f} rad/s target={expected / 1000.0:.3f} "
		f"CV={v_cv:.2f} accepted={accept_pct:.1f}% bins={n_fill}/{COG_LUT_N} median_n={median_n:.0f}"
	)
	if n_fill < int(COG_LUT_N * 0.9):
		raise SystemExit(f"host-learn: sparse {label} pass ({n_fill}/{COG_LUT_N}; need >=90%)")
	means = np.zeros(COG_LUT_N, dtype=np.float64)
	stable_effort = e[stable]
	for b in np.flatnonzero(filled):
		means[b] = float(np.median(stable_effort[bins == b]))
	x = np.flatnonzero(filled)
	xp = np.concatenate((x[-1:] - COG_LUT_N, x, x[:1] + COG_LUT_N))
	fp = np.concatenate((means[x[-1:]], means[x], means[x[:1]]))
	missing = np.flatnonzero(~filled)
	means[missing] = np.interp(missing, xp, fp)
	return means


def host_learn(
	dev, seconds: float, revs: float, passes: int = 3, invert: bool = False
) -> np.ndarray:
	"""Average steady forward/reverse effort by angle to reject friction and lag."""
	send(dev, 0x09)  # POS deliberately skips cog FF
	time.sleep(0.05)
	wait_mode(dev, 0, timeout=3.0)
	span = int(revs * MRAD_2PI)
	print(f"host-learn {passes}x continuous bidirectional (hands off)...")
	forwards = []
	reverses = []
	for run in range(passes):
		print(f"pair {run + 1}/{passes}")
		forwards.append(collect_pass(dev, span, seconds, "forward"))
		reverses.append(collect_pass(dev, -span, seconds, "reverse"))
	forward = np.median(np.stack(forwards), axis=0)
	reverse = np.median(np.stack(reverses), axis=0)
	if passes > 1:
		pairs = np.stack([
			0.5 * (f - np.mean(f) + r - np.mean(r))
			for f, r in zip(forwards, reverses)
		])
		spread = np.std(pairs, axis=0)
		print(
			f"repeatability rms={float(np.sqrt(np.mean(spread**2))):.5f} "
			f"peak={float(np.max(spread)):.5f}"
		)
	fc = forward - np.mean(forward)
	rc = reverse - np.mean(reverse)
	corr = float(np.corrcoef(fc, rc)[0, 1])
	print(f"direction correlation={corr:.3f}")
	if not np.isfinite(corr) or corr < 0.30:
		raise SystemExit("host-learn: forward/reverse LUTs disagree; motion or current loop is not repeatable")
	lut = 0.5 * (forward + reverse)
	# One-bin circular anti-aliasing: suppress ADC/quantization spikes without
	# erasing cog features that span multiple 0.352-degree bins.
	lut = 0.25 * np.roll(lut, 1) + 0.5 * lut + 0.25 * np.roll(lut, -1)
	lut -= np.mean(lut)
	if invert:
		lut = -lut
	peak = float(np.max(np.abs(lut)))
	if peak <= 1e-3:
		raise SystemExit(f"host-learn: |peak|={peak:.6f} too small — check GOTO effort / CUR_LOOP")
	print(f"combined |lut|peak={peak:.4f} invert={invert}")
	return lut.astype(np.float64)


def device_cal(dev) -> None:
	print(f"device COG_CAL (~{COG_CAL_S:.0f}s)...")
	send(dev, 0x08)
	t0 = time.time()
	saw = False
	while time.time() - t0 < 3.0:
		f = read_telem(dev, timeout_ms=100)
		if f is None:
			continue
		if f["mode"] == 11:
			saw = True
			break
		if 1 <= f["mode"] <= 4:
			raise SystemExit(f"still aligning (mode={f['mode']})")
	if not saw:
		raise SystemExit("COG_CAL did not start")
	wait_mode(dev, 0, timeout=COG_CAL_S + 5.0)
	print("IDLE — RAM LUT override active (not flash until --write + rebuild)")


def main() -> int:
	ap = argparse.ArgumentParser(description=__doc__)
	ap.add_argument("--host-learn", action="store_true", help="sweep GOTO; build LUT on host")
	ap.add_argument("--device-cal", action="store_true", help="firmware COGCAL → RAM override")
	ap.add_argument("--write", type=str, default="", help="write src/cog_lut_default.h")
	ap.add_argument("--invert", action="store_true", help="negate LUT (try if FF feels sticky)")
	ap.add_argument("--seconds", type=float, default=24.0)
	ap.add_argument("--revs", type=float, default=12.0, help="revolutions per direction")
	ap.add_argument("--passes", type=int, default=3, help="bidirectional pairs to median")
	ap.add_argument("--no-bootloader", action="store_true")
	ap.add_argument("--skip-start", action="store_true")
	args = ap.parse_args()
	if args.passes < 1:
		ap.error("--passes must be >=1")
	if not args.host_learn and not args.device_cal:
		args.host_learn = True  # default: bake path

	dev = open_dev()
	if not args.skip_start:
		align(dev)
	else:
		wait_mode(dev, 0, timeout=3.0)

	lut = None
	if args.host_learn:
		lut = host_learn(
			dev, args.seconds, args.revs, passes=args.passes, invert=args.invert
		)
		# Gates already enforced inside host_learn before return.
		if args.write:
			write_header(args.write, lut)
		else:
			print("hint: pass --write src/cog_lut_default.h then rebuild+flash to bake")
	if args.device_cal:
		device_cal(dev)

	print("try SPIN: flick soft vs hard — speed should follow, detent reduced if LUT baked/RAM on")
	if not args.no_bootloader:
		print("UPLOAD → UF2")
		try:
			send(dev, 0x7F)
		except usb.core.USBError:
			pass
	return 0


if __name__ == "__main__":
	sys.exit(main())
